### ISSUE TITLE
Nová verzia katalógu požiadaviek

### ISSUE THREAD

**Issue by Spaghettoni** [TIS2020-FMFI/vzduch#15]
Zapracovať všetky pripomienky do katalógu požiadaviek

**Comment by pavelpetrovic** [comment]
Ďakujem za aktualizáciu KP. Doplnil som ešte pár ďalších komentárov a úprav, prosím spracujte ich a ešte raz mi to pošlite na kontrolu. 
[Katalog-poziadaviek-2.docx](https://github.com/TIS2020-FMFI/vzduch/files/5424005/Katalog-poziadaviek-2.docx)

**Comment by ghost** [comment]
[Katalog-poziadaviek-3.docx](https://github.com/TIS2020-FMFI/vzduch/files/5444026/Katalog-poziadaviek-3.docx)
najnovší KP ktorý je aj na teamse.

**Comment by pavelpetrovic** [comment]
Veľmi pekne ste to už spracovali, veľká pochvala!
Doplnil som už len minimum drobností a asi na dvoch miestach som ešte pridal malú otázočku. Skúste to, prosím, podľa toho doplniť a potom hneď poslať zadávateľom, aby si KP dôkladne prečítali, lebo podľa tohto to idete vyvinúť a dali k nemu svoje pripomienky, alebo ho rovno schválili.
[Katalog-poziadaviek-3-k.docx](https://github.com/TIS2020-FMFI/vzduch/files/5448711/Katalog-poziadaviek-3-k.docx)

**Comment by ghost** [comment]
[Katalog-poziadaviek-SHMU.docx](https://github.com/TIS2020-FMFI/vzduch/files/5464437/Katalog-poziadaviek-SHMU.docx)
Katalóg poslaný do SHMU.

**Comment by Spaghettoni** [comment]
Najnovšia verzia katalógu
[Katalog-poziadaviek_4.docx](https://github.com/TIS2020-FMFI/vzduch/files/5500492/Katalog-poziadaviek_4.docx)

**Comment by Spaghettoni** [comment]
[Katalog-poziadaviek_5.docx](https://github.com/TIS2020-FMFI/vzduch/files/5530945/Katalog-poziadaviek_5.docx)
