### ISSUE TITLE
Návrh používateľského rozhrania

### ISSUE THREAD

**Issue by Spaghettoni** [TIS2020-FMFI/vzduch#18]
Nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom

**Comment by Spaghettoni** [comment]
![UI-SHMU1](https://user-images.githubusercontent.com/24212379/97693846-096b8e80-1aa2-11eb-802c-47c8006fad40.png)
![UI-SHMU2](https://user-images.githubusercontent.com/24212379/97693848-0a9cbb80-1aa2-11eb-9f0f-4fd4b25cc6a8.png)

**Comment by pavelpetrovic** [comment]
ta tabulka stanic bude mat scrollbar? v takom pripadne ho dokreslite, alebo to len v dokumente navrh uvedte pod obrazkom. vdaka.

**Comment by Spaghettoni** [comment]
![image](https://user-images.githubusercontent.com/24212379/98947799-f28f5800-24f5-11eb-95f0-5f7016eb6a5c.png)
![image](https://user-images.githubusercontent.com/24212379/98947822-f91dcf80-24f5-11eb-856d-3409039f1a02.png)
