### ISSUE TITLE
 Návrh implementácie

### ISSUE THREAD

**Issue by Spaghettoni** [TIS2020-FMFI/vzduch#19]
UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky

**Comment by Michal-25** [comment]
UML Component Diagram
[UML Component Diagram - TIS project.pdf](https://github.com/TIS2020-FMFI/vzduch/files/5532497/UML.Component.Diagram.-.TIS.project.pdf)

**Comment by Michal-25** [comment]
UML Class Diagram
[UML Class Diagram - TIS project.pdf](https://github.com/TIS2020-FMFI/vzduch/files/5532500/UML.Class.Diagram.-.TIS.project.pdf)

**Comment by Michal-25** [comment]
UML Sequence Diagram
[UML Sequence Diagram - TIS project.pdf](https://github.com/TIS2020-FMFI/vzduch/files/5532504/UML.Sequence.Diagram.-.TIS.project.pdf)
