### ISSUE TITLE
Vytvoriť dokument na Návrh

### ISSUE THREAD

**Issue by Spaghettoni** [TIS2020-FMFI/vzduch#20]
Vytvoriť dokument v ktorom bude:

-  podrobná špecifikácia vonkajších interfejsov
-  podrobný dátový model perzistentných údajov
-  návrh používateľského rozhrania
-  zrozumiteľný a jednoznačný návrh implementácie

**Comment by pavelpetrovic** [comment]
len pre zaujímavosť: našiel som len správy o tej novej mobilnej stránke, je tam aj znečistenie http://www.shmu.sk/sk/?page=2049&id=1091
