### ISSUE TITLE
Návrh

### ISSUE THREAD

**Issue by ghost** [TIS2020-FMFI/vzduch#53]
[TIS.vzduch.navrh (1)-merged.pdf](https://github.com/TIS2020-FMFI/vzduch/files/5638498/TIS.vzduch.navrh.1.-merged.pdf)

**Comment by Michal-25** [comment]
[TIS vzduch návrh.docx](https://github.com/TIS2020-FMFI/vzduch/files/5652764/TIS.vzduch.navrh.docx)
